// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"ticketing/ent/genre"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Genre is the model entity for the Genre schema.
type Genre struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GenreQuery when eager-loading is set.
	Edges        GenreEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GenreEdges holds the relations/edges for other nodes in the graph.
type GenreEdges struct {
	// Concerts holds the value of the concerts edge.
	Concerts []*Concert `json:"concerts,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ConcertsOrErr returns the Concerts value or an error if the edge
// was not loaded in eager-loading.
func (e GenreEdges) ConcertsOrErr() ([]*Concert, error) {
	if e.loadedTypes[0] {
		return e.Concerts, nil
	}
	return nil, &NotLoadedError{edge: "concerts"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Genre) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case genre.FieldName:
			values[i] = new(sql.NullString)
		case genre.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Genre fields.
func (ge *Genre) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case genre.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ge.ID = *value
			}
		case genre.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				ge.Name = value.String
			}
		default:
			ge.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Genre.
// This includes values selected through modifiers, order, etc.
func (ge *Genre) Value(name string) (ent.Value, error) {
	return ge.selectValues.Get(name)
}

// QueryConcerts queries the "concerts" edge of the Genre entity.
func (ge *Genre) QueryConcerts() *ConcertQuery {
	return NewGenreClient(ge.config).QueryConcerts(ge)
}

// Update returns a builder for updating this Genre.
// Note that you need to call Genre.Unwrap() before calling this method if this Genre
// was returned from a transaction, and the transaction was committed or rolled back.
func (ge *Genre) Update() *GenreUpdateOne {
	return NewGenreClient(ge.config).UpdateOne(ge)
}

// Unwrap unwraps the Genre entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ge *Genre) Unwrap() *Genre {
	_tx, ok := ge.config.driver.(*txDriver)
	if !ok {
		panic("ent: Genre is not a transactional entity")
	}
	ge.config.driver = _tx.drv
	return ge
}

// String implements the fmt.Stringer.
func (ge *Genre) String() string {
	var builder strings.Builder
	builder.WriteString("Genre(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ge.ID))
	builder.WriteString("name=")
	builder.WriteString(ge.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Genres is a parsable slice of Genre.
type Genres []*Genre
