// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ticketing/ent/concert"
	"ticketing/ent/genre"
	"ticketing/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// GenreUpdate is the builder for updating Genre entities.
type GenreUpdate struct {
	config
	hooks    []Hook
	mutation *GenreMutation
}

// Where appends a list predicates to the GenreUpdate builder.
func (gu *GenreUpdate) Where(ps ...predicate.Genre) *GenreUpdate {
	gu.mutation.Where(ps...)
	return gu
}

// SetName sets the "name" field.
func (gu *GenreUpdate) SetName(s string) *GenreUpdate {
	gu.mutation.SetName(s)
	return gu
}

// AddConcertIDs adds the "concerts" edge to the Concert entity by IDs.
func (gu *GenreUpdate) AddConcertIDs(ids ...uuid.UUID) *GenreUpdate {
	gu.mutation.AddConcertIDs(ids...)
	return gu
}

// AddConcerts adds the "concerts" edges to the Concert entity.
func (gu *GenreUpdate) AddConcerts(c ...*Concert) *GenreUpdate {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return gu.AddConcertIDs(ids...)
}

// Mutation returns the GenreMutation object of the builder.
func (gu *GenreUpdate) Mutation() *GenreMutation {
	return gu.mutation
}

// ClearConcerts clears all "concerts" edges to the Concert entity.
func (gu *GenreUpdate) ClearConcerts() *GenreUpdate {
	gu.mutation.ClearConcerts()
	return gu
}

// RemoveConcertIDs removes the "concerts" edge to Concert entities by IDs.
func (gu *GenreUpdate) RemoveConcertIDs(ids ...uuid.UUID) *GenreUpdate {
	gu.mutation.RemoveConcertIDs(ids...)
	return gu
}

// RemoveConcerts removes "concerts" edges to Concert entities.
func (gu *GenreUpdate) RemoveConcerts(c ...*Concert) *GenreUpdate {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return gu.RemoveConcertIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (gu *GenreUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, gu.sqlSave, gu.mutation, gu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (gu *GenreUpdate) SaveX(ctx context.Context) int {
	affected, err := gu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (gu *GenreUpdate) Exec(ctx context.Context) error {
	_, err := gu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gu *GenreUpdate) ExecX(ctx context.Context) {
	if err := gu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (gu *GenreUpdate) check() error {
	if v, ok := gu.mutation.Name(); ok {
		if err := genre.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Genre.name": %w`, err)}
		}
	}
	return nil
}

func (gu *GenreUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := gu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(genre.Table, genre.Columns, sqlgraph.NewFieldSpec(genre.FieldID, field.TypeUUID))
	if ps := gu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := gu.mutation.Name(); ok {
		_spec.SetField(genre.FieldName, field.TypeString, value)
	}
	if gu.mutation.ConcertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   genre.ConcertsTable,
			Columns: genre.ConcertsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concert.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := gu.mutation.RemovedConcertsIDs(); len(nodes) > 0 && !gu.mutation.ConcertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   genre.ConcertsTable,
			Columns: genre.ConcertsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concert.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := gu.mutation.ConcertsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   genre.ConcertsTable,
			Columns: genre.ConcertsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concert.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, gu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{genre.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	gu.mutation.done = true
	return n, nil
}

// GenreUpdateOne is the builder for updating a single Genre entity.
type GenreUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GenreMutation
}

// SetName sets the "name" field.
func (guo *GenreUpdateOne) SetName(s string) *GenreUpdateOne {
	guo.mutation.SetName(s)
	return guo
}

// AddConcertIDs adds the "concerts" edge to the Concert entity by IDs.
func (guo *GenreUpdateOne) AddConcertIDs(ids ...uuid.UUID) *GenreUpdateOne {
	guo.mutation.AddConcertIDs(ids...)
	return guo
}

// AddConcerts adds the "concerts" edges to the Concert entity.
func (guo *GenreUpdateOne) AddConcerts(c ...*Concert) *GenreUpdateOne {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return guo.AddConcertIDs(ids...)
}

// Mutation returns the GenreMutation object of the builder.
func (guo *GenreUpdateOne) Mutation() *GenreMutation {
	return guo.mutation
}

// ClearConcerts clears all "concerts" edges to the Concert entity.
func (guo *GenreUpdateOne) ClearConcerts() *GenreUpdateOne {
	guo.mutation.ClearConcerts()
	return guo
}

// RemoveConcertIDs removes the "concerts" edge to Concert entities by IDs.
func (guo *GenreUpdateOne) RemoveConcertIDs(ids ...uuid.UUID) *GenreUpdateOne {
	guo.mutation.RemoveConcertIDs(ids...)
	return guo
}

// RemoveConcerts removes "concerts" edges to Concert entities.
func (guo *GenreUpdateOne) RemoveConcerts(c ...*Concert) *GenreUpdateOne {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return guo.RemoveConcertIDs(ids...)
}

// Where appends a list predicates to the GenreUpdate builder.
func (guo *GenreUpdateOne) Where(ps ...predicate.Genre) *GenreUpdateOne {
	guo.mutation.Where(ps...)
	return guo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (guo *GenreUpdateOne) Select(field string, fields ...string) *GenreUpdateOne {
	guo.fields = append([]string{field}, fields...)
	return guo
}

// Save executes the query and returns the updated Genre entity.
func (guo *GenreUpdateOne) Save(ctx context.Context) (*Genre, error) {
	return withHooks(ctx, guo.sqlSave, guo.mutation, guo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (guo *GenreUpdateOne) SaveX(ctx context.Context) *Genre {
	node, err := guo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (guo *GenreUpdateOne) Exec(ctx context.Context) error {
	_, err := guo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (guo *GenreUpdateOne) ExecX(ctx context.Context) {
	if err := guo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (guo *GenreUpdateOne) check() error {
	if v, ok := guo.mutation.Name(); ok {
		if err := genre.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Genre.name": %w`, err)}
		}
	}
	return nil
}

func (guo *GenreUpdateOne) sqlSave(ctx context.Context) (_node *Genre, err error) {
	if err := guo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(genre.Table, genre.Columns, sqlgraph.NewFieldSpec(genre.FieldID, field.TypeUUID))
	id, ok := guo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Genre.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := guo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, genre.FieldID)
		for _, f := range fields {
			if !genre.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != genre.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := guo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := guo.mutation.Name(); ok {
		_spec.SetField(genre.FieldName, field.TypeString, value)
	}
	if guo.mutation.ConcertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   genre.ConcertsTable,
			Columns: genre.ConcertsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concert.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := guo.mutation.RemovedConcertsIDs(); len(nodes) > 0 && !guo.mutation.ConcertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   genre.ConcertsTable,
			Columns: genre.ConcertsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concert.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := guo.mutation.ConcertsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   genre.ConcertsTable,
			Columns: genre.ConcertsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concert.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Genre{config: guo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, guo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{genre.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	guo.mutation.done = true
	return _node, nil
}
