apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: cs203
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        type: frontend
    spec:
      terminationGracePeriodSeconds: 3
      containers:
        - name: frontend
          imagePullPolicy: Always
          image: tigercxx/cs203-frontend:v2.2.0
          resources:
            limits:
              memory: "1000Mi"
              cpu: "400m"
          env:
            - name: REACT_APP_AUTH_API_URL
              value: "https://sg1.biddlr.com/auth"
            - name: TICKETING_API_URL
              value: "https://sg1.biddlr.com/ticketing"
            - name: PAYMENT_API_URL
              value: "https://sg1.biddlr.com/payment"
            - name: QUEUE_API_URL
              value: "https://sg1.biddlr.com/queue"
            - name: "QUEUE_WEBSOCKET_URL"
              value: "wss://sg1.biddlr.com/queue/queue"
            - name: ENVIRONMENT
              value: "development"
            - name: "PRODUCTION_URL"
              value: "sg1.biddlr.com"
            - name: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
              value: pk_test_51Kia4HFtg42uLJvvAAj23WtQbTAzT8ZFK9z1uhIsgK848qUvMxCIerOmOC1ldbyRi19lzI7nq6uvGdxmu6Q7bJmV00sMf1m1da # xian xiang one
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: cs203
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
