apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  namespace: cs203
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
        type: payment
    spec:
      terminationGracePeriodSeconds: 3
      containers:
        - name: payment
          readinessProbe:
            httpGet:
              path: /payment/health
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 10
          imagePullPolicy: Always
          image: tigercxx/cs203-payment:v2.2.0
          resources:
            limits:
              memory: "500Mi"
              cpu: "200m"
          env:
            - name: POSTGRES_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: db-redis-secrets
                  key: POSTGRES_ADDRESS
            - name: REDIS_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: db-redis-secrets # not used yet
                  key: REDIS_ADDRESS
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secrets
                  key: STRIPE_SECRET_KEY
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: stripe-secrets
                  key: STRIPE_WEBHOOK_SECRET
            - name: RESEND_API_KEY
              valueFrom:
                secretKeyRef:
                  name: resend-api
                  key: RESEND_API_KEY
            - name: ENVIRONMENT
              value: "kubernetes"
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: cs203
spec:
  type: NodePort
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30084
