apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-deployment
  namespace: cs203
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      labels:
        app: queue
        type: queue
    spec:
      terminationGracePeriodSeconds: 3
      containers:
        - name: queue
          readinessProbe:
            httpGet:
              path: /queue/health
              port: 8500
            initialDelaySeconds: 5
            periodSeconds: 10
          imagePullPolicy: Always
          image: tigercxx/cs203-queue:v2.2.0
          resources:
            limits:
              memory: "500Mi"
              cpu: "200m"
          env:
            - name: REDIS_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: db-redis-secrets
                  key: REDIS_ADDRESS
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: SECRET_KEY
          ports:
            - containerPort: 8500
---
apiVersion: v1
kind: Service
metadata:
  name: queue-service
  namespace: cs203
  annotations:
    cloud.google.com/backend-config: '{"default":"ws-backend-config"}'
spec:
  type: NodePort
  selector:
    app: queue
  ports:
    - protocol: TCP
      port: 8500
      targetPort: 8500
      nodePort: 30085
