// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Concert is the predicate function for concert builders.
type Concert func(*sql.Selector)

// ConcertSession is the predicate function for concertsession builders.
type ConcertSession func(*sql.Selector)

// Genre is the predicate function for genre builders.
type Genre func(*sql.Selector)

// Section is the predicate function for section builders.
type Section func(*sql.Selector)

// Ticket is the predicate function for ticket builders.
type Ticket func(*sql.Selector)
