name: Dev CI Unit Test

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.3'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      working-directory: frontend 
      run: pnpm install

    - name: Run tests
      working-directory: frontend 
      run: pnpm test 

    - name: Install Go dependencies
      working-directory: ticketing
      run: go mod tidy && go mod download

    - name: Run Go tests
      working-directory: ticketing/test
      run: go test ./...